### PR TITLE
chore: bump up anchor crates to 0.30.0

### LINKED ISSUE #59: Upgrade to Anchor 0.30.0
Now that the Token Extension changes are live, we should build off the Crate rather than the GitHub. Will allow us to publish a crate here and also stay on top of newest changes

### PR DESCRIPTION
**Pull request by sunguru98**
Closes #59 and #55

### CODE REVIEW

**Review by kespinola — APPROVED** [review]

**Comment by kespinola** [comment]
I believe this is similar change and maybe closed by this PR

https://github.com/wen-community/wen-new-standard/pull/52

@Bhargavamacha

**Review by balmy-gazebo — APPROVED** [review]

**Comment by balmy-gazebo** [comment]
Looks good, thanks for that. I'll verify the tests run and then merge it.

**Comment by sunguru98** [comment]
Screenshot 2024-04-18 at 5 53 14 PM

The tests passed under the local anchor fork (which had the fix for stack violation error). Hence the tests will continue to pass once the PR for 0.30.1 in anchor merges.

**Review by kespinola — APPROVED** [review]

**Review by kespinola — COMMENTED** [review]
@sunguru98 please remove the anchor binary in the repo. No longer needed after official release.

**Comment by sunguru98** [comment]
Already removed @kespinola

**Review by balmy-gazebo — APPROVED** [review]

**Pull request merged**
